### PR TITLE
@‍EnvironmentState and support for the Observable macro

### PR DESCRIPTION
**Pull request by groue**
Closing this pull request.

It looks like it is impossible to make it work as expected. In particular, in the following sample code, changing the score from `ScoreView` always triggers a refresh of `NameView`. This does not happen with the regular `@State`, and I was unable to reproduce this behavior despite much frobnication with the `@Observable` runtime.

```swift
@Observable
class Player {
    var name: String
    var score: Int
    
    init(name: String, score: Int) {
        self.name = name
        self.score = score
    }
}

struct TestView: View {
    @EnvironmentState var model: Model
    init() {
        _model = EnvironmentState { _ in
            // Ignore the environment, this is just a debugging example
            Model(name: "Paul", score: 0)
        }
    }
    
    var body: some View {
        Self._printChanges()
        return VStack {
            NameView(name: $model.name)
            ScoreView(score: $model.score)
        }
    }
}

struct NameView: View {
    @Binding var name: String
    
    var body: some View {
        Self._printChanges()
        return VStack {
            Text(name)
            Button("Change Name") {
                // Triggers a refresh of ScoreView :-(
                name = UUID().uuidString
            }
        }
    }
}

struct ScoreView: View {
    @Binding var score: Int
    
    var body: some View {
        Self._printChanges()
        return VStack {
            Text("\(score)")
            Button("Change Score") {
                // Triggers a refresh of NameView :-(
                score += 1
            }
        }
    }
}

```

### CODE REVIEW

**Comment by Mohamad-Kredly** [comment]
Hi @groue! It might be worth to revisit this as when I was running your debug code with [EnvironmentState](https://github.com/groue/GRDBQuery/blob/EnvironmentState/Sources/GRDBQuery/EnvironmentState.swift) on the main branch I didn't get any refreshes of uninvolved views. Tests were done on an iOS 18.3 simulator. 

Changes were tracked by the print logs and random foreground color in the views

**Comment by groue** [comment]
Hi @Mohamad-Kredly. This PR was never merged. It contains unfinished and probably invalid code.

**Comment by Mohamad-Kredly** [comment]
Yeah, I found it while looking into adding support for the Observable macro. Any plans to support it?

**Comment by groue** [comment]
These days I'm using: https://gist.github.com/groue/28369e1d99319c90dea5fb8cd305cb39

For example, given this Observable class:

```swift
@MainActor @Observable final class MyViewModel {
    var text = ""
    private let myService: MyService

    init(myService: MyService) {
        self.myService = myService
        performSideEffect()
    }

    func submit() {
        // Do whatever with self.text
    }

    func performSideEffect() {
        // Whatever. For example start observing the database.
    }
}
```

I can define the view as below:

```swift
struct MyView: View {
    // Load the service from the environment
    @Environment(\.myService) private var myService

    var body: some View {
        WithBindable {
             // Guarantees single instantiation of the view model.
             // The side-effect of view model instantiation will be
             // performed only once.
             MyViewModel(myService: myService)
        } content: { $viewModel in
            TextField("Text", text: $viewModel.text)
                .onSubmit { viewModel.submit() }
        }
    }
}
```

Alternatively:

```swift
struct MyView: View {
    @Environment(\. myService) private var myService

    var body: some View {
        WithBindable {
             // Guarantees single instantiation of the view model.
             // The side-effect of view model instantiation will be
             // performed only once.
             MyViewModel(myService: myService)
        } content: { $viewModel in
            ContentView(viewModel: viewModel)
        }
    }
}

private var ContentView: View {
    @Bindable var viewModel: MyViewModel

    var body: some View {
        TextField("Text", text: $viewModel.text)
            .onSubmit { viewModel.submit() }
    }
}
```

I'm not sure this code will ship in GRDBQuery. But GRDBQuery doc could link to it, I agree. `ObservableObject` is a thing of the past, now.

**Pull request closed without merging**
